config/routes.rb
Rails.application.routes.draw do
  root 'schedules#new'
  devise_for :users

  resources :schedules, only: [:show, :new, :create] 

  namespace :admin do
    resources :employees do
      collection do
        get :report
      end

      member do
        get :api
      end
    end

    resources :archives
    root to: 'employees#index'
  end
end

app/models/admin/employee.rb
class Admin::Employee < ApplicationRecord
    has_many :schedules

    def self.get_joined_employee
        Admin::Employee
            .select("employees.id, first_name, last_name, date(start) day, time(start) start, time(stop) stop, sum(schedules.hours_per_day) hours_per_month, employee_id")
            .joins("LEFT JOIN schedules ON employees.id=schedules.employee_id")
            .group(:id)
            # .where("(schedules.start>'#{ti}' OR schedules.start is null) AND (schedules.stop<'#{tf}' or schedules.stop is null)")
    end

    def total_per_month
        t = Time.now
        ti = t.beginning_of_month
        tf = t.end_of_month

        if day
            if day > ti && day < tf
                ('<span class="badge badge-pill badge-soft-success font-size-12">'+hours_per_month.to_s+' Horas</span>').html_safe
            else
                '<span class="badge badge-pill badge-soft-success font-size-12">NO TIENE HORAS EN ESTE MES</span>'.html_safe
            end
        else
            '<span class="badge badge-pill badge-soft-danger font-size-12">NO TIENE HORAS</span>'.html_safe
        end
    end

    private
        def get_csv(employees, options={})
            CSV.generate(options) do |csv|
                csv << ['ID', 'NOMBRES', 'DÍA', 'ENTRADA', 'SALIDA', 'SUBTOTAL_DE_HORAS']
    
                total = 0
                employees.each do |employee|
                    if employee.day
                        csv << [employee.id, employee.first_name+" "+employee.last_name, employee.day, employee.start, employee.stop, employee.hours_per_month]
                        total += employee.hours_per_month
                    else
                        csv << [employee.id, employee.first_name+" "+employee.last_name, "----------", "----------", "----------", "NO TIENE HORAS"]
                    end
                end

                csv << ["TOTAL_HORAS: ", total]
            end
        end

        def get_html(employees)
            html_str = '<html><head><title>Reporte</title></head><body><div style="padding: 5vh;"><h2 style="text-align: center !important;">Reporte</h2><hr><br><div class="table-responsive">'
            html_str += '<table border="2" class="table" style="width: 100%; border-collapse: collapse;"><thead><tr><th width="10%">#ID</th><th width="20%">Nombres</th><th width="20%">Día</th><th width="15%">Entrada</th><th width="15%">Salida</th><th width="20%">Subtotal-Horas</th></tr></thead><tbody>'

            total = 0

            if employees.length != 0
                employees.each do |employee|
                    html_str += 
                        "<tr>
                            <td>##{ employee.id }</td>
                            <td>#{ employee.first_name } #{ employee.last_name }</td>"

                    if employee.day
                        html_str += "
                            <td>#{ employee.day }</td>
                            <td>#{ employee.start }</td>
                            <td>#{ employee.stop }</td>
                            <td>#{ e.hours_per_month.to_s }</td>"

                        total += employee.hours_per_month
                    else
                        html_str += '
                            <td>----------</td>
                            <td>----------</td>
                            <td>----------</td>
                            <td align="right">"NO TIENE HORAS"</td>'
                    end

                    html_str += '</tr>'
                end
            else
                html_str += '
                    <tr style="text-align: center !important;">
                        <td colspan="6">No hay datos que mostrar.</td>
                    </tr>'
            end

            html_str += '</tbody></table><br><p>Total de horas: '+total.to_s+'</p></div></div></body></html>'
        end
end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < Admin::ApplicationController
    before_action :set_admin_employee, only: %i[ show edit update destroy api]

    def index
        @admin_employees = Admin::Employee.get_joined_employee
    end

    def show
    end

    def new
        @admin_employee = Admin::Employee.new
    end

    def edit
    end

    def create
        @admin_employee = Admin::Employee.new(admin_employee_params)

        respond_to do |format|
            if @admin_employee.save
                format.html { redirect_to admin_employee_url(@admin_employee), notice: "Employee was successfully created." }
                format.json { render :show, status: :created, location: @admin_employee }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @admin_employee.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
            if @admin_employee.update(admin_employee_params)
                format.html { redirect_to admin_employee_url(@admin_employee), notice: "Employee was successfully updated." }
                format.json { render :show, status: :ok, location: @admin_employee }
            else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @admin_employee.errors, status: :unprocessable_entity }
            end
        end
    end

    def api
        res = @admin_employee
                .schedules
                .select("id, '<b>Día laboral</b> <br><br> Entrada: ' || start || '<br><br>Salida:' || stop title, start, stop")

        render json: res
    end

    def destroy
        @admin_employee.destroy

        respond_to do |format|
            format.html { redirect_to admin_employees_url, notice: "Employee was successfully destroyed." }
            format.json { head :no_content }
        end
    end


    def report
        render plain: 'aquí está el reporte'
=begin
        todos       = report_params[:todos].to_i
        employee_id = report_params[:employee_id]
        date_month  = report_params[:date_month]

        if user_signed_in?
            t = Time.now.strftime('%d-%m-%Y');

            name = t+"_"
            description = "<b>fecha: </b> #{t}<br>"
            attack = request.format.symbol.to_s
            file = nil

            if todos == 1
                name += "todos_mes-#{date_month}_"
                description += "<b>empleado: </b> todos<br><b>#mes: </b> #{date_month}<br>"
                @employees = Employee
                            .select("employees.id, first_name, last_name, date(start) day, time(start) start, time(stop) stop, sum(schedules.hours_per_day) hours_per_month, employee_id")
                            .joins("LEFT JOIN schedules ON employees.id=schedules.employee_id")
                            .where("cast(strftime('%m', schedules.start) as integer)=#{date_month}")
                            .group(:id)
            else
                name += "empleado-#{employee_id}_mes-#{date_month}_"
                description += "<b>empleado: </b> #{employee_id}<br><b>#mes: </b> #{date_month}<br>"
                @employees = Employee
                            .select("employees.id, first_name, last_name, date(start) day, time(start) start, time(stop) stop, sum(schedules.hours_per_day) hours_per_month, employee_id")
                            .joins("LEFT JOIN schedules ON employees.id=schedules.employee_id")
                            .where("cast(strftime('%m', schedules.start) as integer)=#{date_month} AND schedules.employee_id=#{employee_id}")
                            .group(:id)
            end

            name = "#{name}.#{attack}"
            description += "<b>tipo: </b> #{attack}"

            archives = Archive.all
            archives.each do |archive|
                if archive.name == name
                    file = url_for(archive.file)
                    break
                end
            end

            unless file
                case attack
                    when 'html'
                        file = get_html(@employees) # html_str
                    when 'csv'
                        file = get_csv(@employees) # csv_str
                    when 'xls'
                        file = get_csv(@employees, col_sep: "\t") # xls_str
                end

                @archive = Archive.new(name: name, description: description)
                @archive.file.attach(io: StringIO.new(file), filename: name)
                @archive.save
            end

            respond_to do |format|
                if @archive
                    # SE HA CREADO UN NUEVO ARCHIVO
                    format.html { send_data file, filename: name }
                    format.csv  { send_data file, filename: name }
                    format.xls  { send_data file, filename: name }
                    # format.xls {send_data @employees.to_csv(col_sep: "\t") }E
                else
                    # SE REDIRECCIONARÁ A UN ARCHIVO YA CREADO
                    format.html { redirect_to file }
                    format.csv  { redirect_to file }
                    format.xls  { redirect_to file }
                end
            end
        else
            redirect_to root_path
        end
=end
    end

    private
        def set_admin_employee
            @admin_employee = Admin::Employee.find(params[:id])
        end

        def admin_employee_params
            params.require(:admin_employee).permit(:first_name, :last_name)
        end

        # def report_params
        #     params.permit(:todos, :employee_id, :date_month)
        # end
end

app/views/admin/employees/_form.html.erb
<%= form_with(model: admin_employee, local: true) do |form| %>
	<div class="card-body">
		<% if admin_employee.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(admin_employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

				<ul>
					<% admin_employee.errors.full_messages.each do |message| %>
						<li><%= message %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<div class="row form-group">
			<%= form.label :first_name, :class => "col-md-4 col-form-label" %>
			<div class="col-md-8">
				<%= form.text_field :first_name, :required => true, :class => "form-control" %>
			</div>
		</div>

		<div class="row form-group">
			<%= form.label :last_name, :class => "col-md-4 col-form-label" %>
			<div class="col-md-8">
				<%= form.text_field :last_name, :required => true, :class => "form-control" %>
			</div>
		</div>
	</div>
	<div class="card-footer">
		<%= form.submit :class => "btn btn-primary" %>
		<%= link_to 'Back', admin_employees_path, class: "btn btn-danger" %>
	</div>
<% end %>

app/views/admin/employees/edit.html.erb
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h4>Editing Employee</h4>
            </div>
            <div class="card-body">
                <%= render 'form', admin_employee: @admin_employee %>
            </div>
        </div>
    </div>
</div>

app/views/admin/employees/index.html.erb
<% if @admin_employees.length != 0 %>
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead class="thead-light">
                <tr class="text-center">
                    <th width="10%">#Id</th>
                    <th width="20%">Nombres</th>
                    <th width="20%">Apellidos</th>
                    <th width="30%">Total por mes</th>
                    <th width="20%">Opciones</th>
                </tr>
            </thead>
            <tbody>
                <% @admin_employees.each do |admin_employee| %>
                    <tr>
                        <td class="text-right"><%= admin_employee.id %></td>
                        <td><%= admin_employee.first_name %></td>
                        <td><%= admin_employee.last_name %></td>
                        <td class="text-right"><%= admin_employee.total_per_month %></td>
                        <td>
                            <%= link_to 'Calendar', admin_employee %> | 
                            <%= link_to 'Edit', edit_admin_employee_path(admin_employee) %> | 
                            <%= link_to 'Destroy', admin_employee, method: :delete, data: { confirm: 'Are you sure?' } %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
    <div class="text-right">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
            Mis reportes
        </button>
    </div>
<% else %>
    <div class="row justify-content-center pt-3">
        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">Hey!</h5>
                    <!--h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6-->
                    <p class="card-text">No hay empleados registrados en este sistema. Si desea, puede crear nuevos empleados ya que usted es el administrador y tiene la capacidad de hacerlo.</p>
                    <%= link_to 'Crear', new_admin_employee_path, class: "card-link" %>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/admin/employees/new.html.erb
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h4>New Employee</h4>
            </div>
            <%= render 'form', admin_employee: @admin_employee %>
        </div>
    </div>
</div>

app/views/admin/employees/report.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
	xmlns:o="urn:schemas-microsoft-com:office:office"
	xmlns:x="urn:schemas-microsoft-com:office:excel"
	xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
	xmlns:html="http://www.w3.org/TR/REC-html40">
	<Worksheet ss:Name="Sheet1">
		<Table>
			<Row>
				<Cell><Data ss:Type="String">#ID              </Data></Cell>
				<Cell><Data ss:Type="String">NOMBRES          </Data></Cell>
				<Cell><Data ss:Type="String">DÍA              </Data></Cell>
				<Cell><Data ss:Type="String">ENTRADA          </Data></Cell>
				<Cell><Data ss:Type="String">SALIDA           </Data></Cell>
				<Cell><Data ss:Type="String">SUBTOTAL_DE_HORAS</Data></Cell>
			</Row>
			<% total = 0 %>
			<% @employees.each do |employee| %>
				<Row>
					<Cell><Data ss:Type="Number"><%= employee.id %></Data></Cell>
					<Cell><Data ss:Type="String"><%= employee.first_name %> <%= employee.last_name %></Data></Cell>
					<% if employee.day %>
						<Cell><Data ss:Type="String"><%= employee.day %></Data></Cell>
						<Cell><Data ss:Type="String"><%= employee.start %></Data></Cell>
						<Cell><Data ss:Type="String"><%= employee.stop %></Data></Cell>
						<Cell><Data ss:Type="String"><%= employee.hours_per_month %></Data></Cell>

						<% total += employee.hours_per_month %>
					<% else %>
						<Cell><Data ss:Type="String">----------</Data></Cell>
						<Cell><Data ss:Type="String">----------</Data></Cell>
						<Cell><Data ss:Type="String">----------</Data></Cell>
						<Cell><Data ss:Type="String"><%= "NO TIENE HORAS" %></Data></Cell>
					<% end %>
				</Row>
			<% end %>
			<Row></Row>
			<Row></Row>
			<Row></Row>
			<Row></Row>
			<Row>
				<Cell><Data ss:Type="String">TOTAL_HORAS: </Data></Cell>
				<Cell><Data ss:Type="String"><%= total %></Data></Cell>
			</Row>
		</Table>
	</Worksheet>
</Workbook>

app/views/admin/employees/show.html.erb
<div id="wrap">
    <%= link_to 'Edit', edit_admin_employee_path(@admin_employee) %> |
    <%= link_to 'Back', admin_employees_path %>

    <div id='calendar'></div>
    <div style='clear:both'></div>
</div>

<script>
    App.new('EmployeesCalendar', {
        apiUrl: '<%= api_admin_employee_path %>'
    });
</script>