config/routes.rb
Rails.application.routes.draw do
  root 'schedules#new'
  devise_for :users

  resources :schedules, only: [:show, :new, :create] 

  namespace :admin do
    resources :employees do
      collection do
        get :report
      end

      member do
        get :api
      end
    end

    resources :archives
    root to: 'employees#index'
  end
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    def self.create_(params)
        today = Time.zone.now.strftime("%Y-%m-%d")

        if today == params[:day]
            case params[:type].to_i
            when 1
                Schedule.save_work_start(params)
            when 0
                Schedule.save_work_stop(params)
            else
                { status: :danger, message: 'Tipo inválido.' }
            end
        else
            { status: :danger, message: 'La fecha no es la correcta.' }
        end
    end

    private
        def self.save_work_start(params)
            day = Date.parse(params[:day])
            b = day.beginning_of_day
            e = day.end_of_day
            full_date = Time.parse(params[:day] + ' ' + params[:time])

            schedule = Schedule.find_or_create_by(start: b..e, employee_id: params[:employee_id])

            if schedule.start
                { status: :danger, message: 'Ya hay un entrada con esta fecha.' }
            else
                schedule.start = params[:day] + ' ' + params[:time]

                if schedule.save
                    { status: :created, message: 'La entrada fue creada correctamente.' }
                else
                    { status: :unprocessable_entity, message: schedule.errors }
                end
            end
        end

        def self.save_work_stop(params)
            day = Date.parse(params[:day])
            b = day.beginning_of_day
            e = day.end_of_day
            full_date = Time.parse(params[:day] + ' ' + params[:time])

            schedule = Schedule.find_by(start: b..e, stop: nil, employee_id: params[:employee_id])

            if schedule
                schedule.stop = full_date
                schedule.hours_per_day = (full_date - schedule.start)/3600

                if schedule.save
                    { status: :ok, message: 'La salida fue guardada correctamente.' }
                else
                    { status: :unprocessable_entity, message: schedule.errors }
                end
            else
                { status: :danger, message: 'No existe una entrada a la cual darle salida.' }
            end
        end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
    before_action :set_schedule, only: %i[ show edit update destroy ]

    def show
    end

    def new
        @employees = Admin::Employee.all
        @employee  = Admin::Employee.new
    end

    def create
        schedule = Schedule.create_(schedule_params)

        respond_to do |format|
            if schedule[:status]
                format.html { redirect_to @schedule, notice: 'El horario fue creado correctamente.' }
                format.json { render :show, status: :created, location: @schedule }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @schedule.errors, status: :unprocessable_entity }
            end
        end
    end

    private
        def set_schedule
            @schedule = Schedule.find(params[:id])
        end

        def schedule_params
            params.require(:schedule).permit(:day, :time, :type, :employee_id)
        end
end

app/views/schedules/new.html.erb
<div class="row justify-content-center">
    <div class="col-md-8 col-lg-4">
        <div class="card">
            <div class="card-header">
                <h4>Marcar entrada/salida</h4>
            </div>
			<div class="card-body">
				<%= render 'layouts/partials/alert' %>

				<%= form_for :schedule, url: schedules_path do |f| %>
					<div class="form-group">
						<%= f.label :day %><br />
						<%= f.date_field :day, autofocus: true, autocomplete: "day", :required => true, class: "form-control" %>						
					</div>

					<div class="form-group">
						<%= f.label :time %><br />
						<%= f.time_field :time, autocomplete: "time", :required => true, class: "form-control" %>
					</div>

					<div class="form-group">
						<%= f.label :type %><br />
						<%= f.select :type, [["entrada", "1"], ["salida", "0"]], {}, :required => true,  class: "form-control" %>
					</div>

					<div class="form-group">
						<%= f.label :employee_id %><br />
						<%= f.collection_select :employee_id, @employees, :id, :first_name, {}, required: true, class: "form-control" %>
					</div>

					<%= f.submit "Save", class: "btn btn-primary btn-block" %>
				<% end %>
			</div>
			<div class="card-footer">
				<%= link_to "Soy administrador", admin_root_path %>
			</div>
        </div>
    </div>
</div>

app/views/schedules/show.html.erb
<div class="row justify-content-center">
	<div class="col-md-6">
		<p id="notice"><%= notice %></p>
		<table class="table table-bordered">
			<tbody>
				<tr>
					<td>
						<b>Go in:</b>
					</td>
					<td>
						<%= @schedule.start %>
					</td>
				</tr>
				<tr>
					<td>
						<b>Go out:</b>
					</td>
					<td>
						<%= @schedule.stop %>
					</td>
				</tr>
				<tr>
					<td>
						<b>employee_id:</b>
					</td>
					<td>
						<%= @schedule.employee_id %>
					</td>
				</tr>
			</tbody>
		</table>
		<div class="text-center">
			<%= link_to 'Back', '/', class: "btn btn-danger" %>
		</div>
	</div>
</div>