config/routes.rb
Rails.application.routes.draw do
  root 'schedules#new'
  devise_for :users

  resources :schedules, only: [:show, :new, :create] 

  namespace :admin do
    resources :employees do
      collection do
        get :report
      end

      member do
        get :api
      end
    end

    resources :archives
    root to: 'employees#index'
  end
end

app/models/admin/archive.rb
class Admin::Archive < ApplicationRecord
    has_one_attached :file
end

app/controllers/admin/archives_controller.rb
class Admin::ArchivesController < Admin::ApplicationController
	before_action :set_admin_archive, only: %i[ show edit update destroy ]

    def index
		@admin_archives = Admin::Archive.all
    end

    def show
    end

    def new
		@admin_archive = Admin::Archive.new
    end

    def edit
    end

    def create
		@admin_archive = Admin::Archive.new(admin_archive_params)
		@admin_archive.file.attach(admin_archive_params[:file])

		respond_to do |format|
			if @admin_archive.save
				format.html { redirect_to admin_archive_url(@admin_archive), notice: "Archive was successfully created." }
				format.json { render :show, status: :created, location: @admin_archive }
			else
				format.html { render :new, status: :unprocessable_entity }
				format.json { render json: @admin_archive.errors, status: :unprocessable_entity }
			end
		end
    end

    def update
		@admin_archive.file.purge
		@admin_archive.file.attach(admin_archive_params[:file])

		respond_to do |format|
			if @admin_archive.update(admin_archive_params)
				format.html { redirect_to admin_archive_url(@admin_archive), notice: "Archive was successfully updated." }
				format.json { render :show, status: :ok, location: @admin_archive }
			else
				format.html { render :edit, status: :unprocessable_entity }
				format.json { render json: @admin_archive.errors, status: :unprocessable_entity }
			end
		end
    end

    def destroy
		@admin_archive.destroy
		@admin_archive.file.purge

		respond_to do |format|
			format.html { redirect_to admin_archive, notice: "Archive was successfully destroyed." }
			format.json { head :no_content }
		end
    end

    private
		def set_admin_archive
			@admin_archive = Admin::Archive.find(params[:id])
		end

		def admin_archive_params
			params.require(:admin_archive).permit(:name, :description, :file)
		end
end

app/views/admin/archives/_form.html.erb
<%= form_with(model: admin_archive, local: true) do |form| %>
	<div class="card-body">
		<% if admin_archive.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(archive.errors.count, "error") %> prohibited this archive from being saved:</h2>

				<ul>
					<% admin_archive.errors.full_messages.each do |message| %>
						<li><%= message %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<div class="row form-group">
			<%= form.label :name, :class => "col-md-4 col-form-label" %>
			<div class="col-md-8">
				<%= form.text_field :name, :required => true, :class => "form-control" %>
			</div>
		</div>

		<div class="row form-group">
			<%= form.label :description, :class => "col-md-4 col-form-label" %>
			<div class="col-md-8">
				<%= form.text_area :description, :required => true, :class => "form-control" %>
			</div>
		</div>

		<% if @archive.file.attached? %>
		<% else %>
			<div class="row form-group">
				<%= form.label :file, :class => "col-md-4 col-form-label" %>
				<div class="col-md-8">
					<%= form.file_field :file, :required => true %>
				</div>
			</div>
		<% end %>
	</div>
	<div class="card-footer">
		<%= form.submit :class => "btn btn-primary" %>
		<%= link_to 'Back', admin_archive_path, class: "btn btn-danger" %>
	</div>
<% end %>

app/views/admin/archives/edit.html.erb
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h4>Editing Archive</h4>
            </div>
            <%= render 'form', admin_archive: @admin_archive %>
        </div>
    </div>
</div>

app/views/admin/archives/index.html.erb
<div class="table-responsive">
	<table class="table table-bordered table-hover">
		<thead class="thead-light">
			<tr class="text-center">
			<th>Name</th>
			<th>Description</th>
			<th>Document</th>
			<th colspan="3">Options</th>
			</tr>
		</thead>

		<tbody>
			<% @admin_archives.each do |admin_archive| %>
			<tr>
				<td><%= admin_archive.name %></td>
				<td><%= sanitize admin_archive.description %></td>
				<td>
					<% if admin_archive.file.attached? %>
						<a target="_blank" href="<%= url_for(admin_archive.file) %>">DESCARGAR</a>
					<% end %>
				</td>
				<td><%= link_to 'Show', admin_archive %></td>
				<td><%= link_to 'Edit', edit_admin_archive_path(admin_archive) %></td>
				<td><%= link_to 'Destroy', admin_archive, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

<br>

<%= link_to 'New Archive', new_admin_archive_path, class: 'btn btn-primary' %>
<%= link_to 'Back', root_path, class: 'btn btn-danger' %>

app/views/admin/archives/new.html.erb
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h4>New Archive</h4>
            </div>
            <%= render 'form', admin_archive: @admin_archive %>
        </div>
    </div>
</div>

app/views/admin/archives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_archive.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @admin_archive.description %>
</p>

<p>
  <% if @admin_archive.file.attached? %>
    <p>
      <strong>File:</strong>
      <br>
      <%= image_tag @admin_archive.file %>
    </p>
  <% end %>
</p>

<%= link_to 'Edit', edit_archive_path(@admin_archive) %> |
<%= link_to 'Back', admin_archives_path %>