config/routes.rb
Rails.application.routes.draw do
  root 'schedules#new'
  devise_for :users

  resources :schedules, only: [:show, :new, :create] 

  namespace :admin do
    resources :employees do
      collection do
        get :report
      end

      member do
        get :api
      end
    end

    resources :archives
    root to: 'employees#index'
  end
end

app/views/layouts/partials/_alert.html.erb
<% if notice || alert %>
    <% if notice %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <b>Hey!</b> <%= notice %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
    <% if alert %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <b>Upsss...!</b> <%= alert %>.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
<% end %>

app/views/layouts/partials/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Generar mi reporte</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group row">
                    <label for="todos" class="col-md-4">Todos los empleados</label>
                    <div class="col-md-8">
                        <%= check_box_tag(:todos, "", true, :onclick => 'habilitarEmpleado()') %>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="employee_id" class="col-md-4 col-form-label">Elija un empleado:</label>
                    <div class="col-md-8">
                        <select name="employee_id" id="employee_id" class="form-control" disabled="disabled">
                            <option value="">----------</option>
                            <% if @employees %>
                                <% @employees.each do |employee| %>
                                    <option value="<%= employee.id %>"><%= employee.first_name %> <%= employee.last_name %></option>
                                <% end %>
                            <% end %>
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="month_id" class="col-md-4 col-form-label">Elija un mes:</label>
                    <div class="col-md-8">
                        <%= select_month(Date.today, {}, :class => 'form-control') %>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="type_file_id" class="col-md-4 col-form-label">Elija un formato:</label>
                    <div class="col-md-8">
                        <select name="type_file_id" id="type_file_id" class="form-control" onchange="cleanGenerator()">
                            <option value="html">HTML</option>
                            <option value="csv">CSV</option>
                            <option value="xls">Excel</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <button type="button" onclick="generateFile()" class="btn btn-success">Generar</button>
                    </div>
                    <div class="col-6 text-right" style="display: none;" id="btnGenerator">
                    </div>
                </div>
            </div>
            <!--div class="modal-footer">
                <%#= link_to "HTML", employees_report_path, class: 'btn btn-outline-success' %>
                <%#= link_to "CSV", employees_path(format: "csv"), class: 'btn btn-outline-success' %>
                <%#= link_to "Excel", employees_path(format: "xls"), class: 'btn btn-outline-success' %>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div-->
        </div>
    </div>
</div>

app/views/layouts/partials/_navbar.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark">
	<%= link_to admin_root_path, class: "navbar-brand" do %>
		Bienvenido, <%= current_user.email %>
	<% end %>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav ml-auto">
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<i class="fas fa-user-circle"></i>
				</a>
				<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
					<%= link_to 'New Employee', new_admin_employee_path, class: "dropdown-item" %>
					<%= link_to 'Edit profile', edit_user_registration_path, :class => 'dropdown-item' %>
					<%= link_to "My files", admin_archives_path, class: "dropdown-item" %>
					<div class="dropdown-divider"></div>
					<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'dropdown-item' %>
				</div>
			</li>
		</ul>
	</div>
</nav>